name: 'Get & Cache Dependencies'
description: 'Get the dependencies (npm ci) and cache them'

runs:
  using: 'composite'
  steps:
    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
