name: Deployment

on:
  push:
  workflow_dispatch:
    branches:
      - main

env:
  VITE_API_URL: ${{ secrets.VITE_API_URL }}

jobs:
  lint:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run Lint
        run: npm run lint
  test:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run Test
        run: npm run test
  build:
    environment: main
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      artifact-name: dist
