name: Deploy Step

on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployed artifact
        required: true
        default: dist
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output Content
        run: ls
      - name: Output API URL
        run: echo "${{ env.VITE_API_URL }}"
      - name: Deploy
        run: echo "Deploying..."
